### ISSUE TITLE
Chiffres sur l'électronique contestables

### ISSUE THREAD

**Issue by asumagic** [QuentinAM/STFW#1]
J'ai trouvé ce repo un peu par hasard et j'ai de gros doutes sur certains chiffres avancés sur l'électronique, donc voilà quelques points qui me paraissent très discutables:

## CO2/kWh

Le chiffre de 280g CO2/kWh doit correspondre à un autre pays ou à une moyenne. En France, on est plutôt entre 50g et 100g de CO2/kWh... Entre 2 et 6 fois moins, ce qui fausse les estimations d'à peu près tout le reste quant à la consommation énergétique.

## Consommation énergétique PC

Pour les du PC de bureau, les 48kWh avancés par mois sur base de 8h/j donne une moyenne instantanée de 200W. Pour une moyenne ce n'est pas forcément déraisonnable, mais l'extrapolation des données sur le fait de laisser la machine allumée 24h/24 par simple multiplication par (24/8) est très erronée pour deux raisons:
- Écran éteint et en idle, la consommation d'un PC de bureau sera *largement* plus faible qu'à pleine charge (probablement de l'ordre des 10 à 50W, peut-être jusqu'à 100W dans les pires cas), *surtout* sur du matériel récent (fruit de pas mal d'améliorations architecturales de la part des fabricants de puce).
- En France, l'énergie est la plus neutre en carbone la nuit.

## Consommation énergétique data et serveurs

Ce serait bien d'avoir une source car certains chiffres qui circulent beaucoup (trop) dans la presse sont [souvent critiqués (à juste titre)](https://www.numerama.com/tech/803201-mesurer-le-co2-selon-les-gigaoctets-consommes-lidee-qui-consterne-le-secteur-du-numerique.html). En tout cas, il faut faire particulièrement attention en faisant des liens entre transferts et consommation électrique. Surtout les chiffres par rapport aux emails qui me paraissent très contestables.

Chiffres à part, je pense que le côté matériel mérite beaucoup plus d'attention (faire au plus de réparation, reconditionné, occasion possible). En situation réelle, je pense que les actions type nettoyage de boîte mail sont beaucoup moins significatives que ce que l'on peut faire côté matériel.

**Comment by QuentinAM** [comment]
Bonjour ! 

Merci pour ton commentaire.
Je vais update tout ça je garantie pas que 100% de ce que je dis est vrai mais j’essaye el plus possible en mettant les sources. Il est vrai que je ne clarifie pas toujours si les chiffres sont du pays ou dans le monde.
Je vais régler tout ça !
